In [1]:
import numpy as np

In [3]:
!pip install numpy

In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print (a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [5]:
print (a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
c = np.array([['m','l','k'],['b','a','string']])

In [10]:
d = np.array([{'a':1, 'b':2, 'c':3}])

In [11]:
print (d)

[{'a': 1, 'b': 2, 'c': 3}]


In [12]:
A = np.ones((2,3))

In [13]:
B = np.zeros ((4,3))

In [14]:
C = np.concatenate ([A,B])

In [15]:
print (c)

[['m' 'l' 'k']
 ['b' 'a' 'string']]


In [16]:
D = np.zeros ((3,4))

In [17]:
E = np.ones((3,2))

In [18]:
F = np.concatenate ([D,E], axis= 1)

In [19]:
print (F)

[[0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1.]]


In [20]:
!pip install Pillow

In [23]:
from PIL import Image
from IPython.display import display

infile = 'hallo.png'

im = Image.open(infile)
im.show()

print(infile, im.format, "%dx%d" %  im.size, im.mode)

hallo.png PNG 1920x1080 RGBA
